# Generated by Django 4.2.5 on 2023-10-20 13:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Houses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uploaded_time', models.DateTimeField(auto_now_add=True)),
                ('image_1', models.ImageField(blank=True, null=True, upload_to='house_images')),
                ('image_2', models.ImageField(blank=True, null=True, upload_to='house_images')),
                ('image_3', models.ImageField(blank=True, null=True, upload_to='house_images')),
                ('location', models.TextField()),
                ('house_make', models.CharField(choices=[('bedsitter', 'bedsitter'), ('mansion', 'mansion'), ('villa', 'villa'), ('bungalow', 'bungalow')], max_length=20)),
                ('bedrooms', models.IntegerField()),
                ('price_per_month', models.DecimalField(decimal_places=2, max_digits=10)),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'houses',
                'ordering': ['uploaded_time'],
            },
        ),
    ]
