# Generated by Django 4.2.5 on 2023-10-20 13:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usersapp', '0002_alter_customuser_options'),
        ('usersapp', '0002_alter_customuser_options_customuser_is_tenant_and_more'),
    ]

    operations = [
    ]
